#include <gst/gst.h>
#include <gst/webrtc/webrtc.h>
#include <gst/sdp/sdp.h>
#include <libsoup/soup.h>
#include <json-glib/json-glib.h>
#include <string.h>

#define RTSP_URL "rtsp://bigEye:traHiLook1@10.0.0.210:554/Streaming/Channels/101"

typedef struct
{
    GstElement *pipeline;
    GstElement *webrtc;
    SoupWebsocketConnection *ws;
} AppState;

static AppState app_state = {NULL, NULL, NULL};

// Callback to send local ICE candidates generated by GStreamer to the browser
static void on_ice_candidate(GstElement *webrtc, guint mline_index, gchar *candidate, gpointer user_data)
{
    if (!app_state.ws || soup_websocket_connection_get_state(app_state.ws) != SOUP_WEBSOCKET_STATE_OPEN)
        return;

    JsonBuilder *builder = json_builder_new();
    json_builder_start_object(builder);
    json_builder_set_member_name(builder, "type");
    json_builder_add_string_value(builder, "candidate");

    json_builder_set_member_name(builder, "candidate");
    json_builder_start_object(builder);
    json_builder_set_member_name(builder, "candidate");
    json_builder_add_string_value(builder, candidate);
    json_builder_set_member_name(builder, "sdpMLineIndex");
    json_builder_add_int_value(builder, mline_index);
    json_builder_end_object(builder);

    json_builder_end_object(builder);

    JsonGenerator *gen = json_generator_new();
    JsonNode *root = json_builder_get_root(builder);
    json_generator_set_root(gen, root);
    gchar *text = json_generator_to_data(gen, NULL);

    soup_websocket_connection_send_text(app_state.ws, text);
    g_print("[ICE] Sending candidate to browser (mline %u): %s\n", mline_index, candidate);

    g_free(text);
    json_node_free(root);
    g_object_unref(builder);
    g_object_unref(gen);
}

// Callback when local SDP Answer is generated
static void on_answer_created(GstPromise *promise, gpointer user_data)
{
    GstWebRTCSessionDescription *answer = NULL;
    const GstStructure *reply = gst_promise_get_reply(promise);
    gst_structure_get(reply, "answer", GST_TYPE_WEBRTC_SESSION_DESCRIPTION, &answer, NULL);
    gst_promise_unref(promise);

    GstPromise *local_desc_promise = gst_promise_new();
    g_signal_emit_by_name(app_state.webrtc, "set-local-description", answer, local_desc_promise);
    gst_promise_unref(local_desc_promise);

    g_print("[Signaling] SDP Answer generated and local description set\n");

    // Convert SDP Answer to text and send to browser via WebSocket
    gchar *sdp_string = gst_sdp_message_as_text(answer->sdp);

    JsonBuilder *builder = json_builder_new();
    json_builder_start_object(builder);
    json_builder_set_member_name(builder, "type");
    json_builder_add_string_value(builder, "answer");
    json_builder_set_member_name(builder, "sdp");
    json_builder_add_string_value(builder, sdp_string);
    json_builder_end_object(builder);

    JsonGenerator *gen = json_generator_new();
    JsonNode *root = json_builder_get_root(builder);
    json_generator_set_root(gen, root);
    gchar *text = json_generator_to_data(gen, NULL);

    if (app_state.ws && soup_websocket_connection_get_state(app_state.ws) == SOUP_WEBSOCKET_STATE_OPEN)
    {
        soup_websocket_connection_send_text(app_state.ws, text);
        g_print("[Signaling] Sent SDP Answer to browser\n");
    }

    g_free(sdp_string);
    g_free(text);
    json_node_free(root);
    g_object_unref(builder);
    g_object_unref(gen);
    gst_webrtc_session_description_free(answer);
}

// Dynamic pad handler for rtspsrc -> rtph264depay
static void on_rtspsrc_pad_added(GstElement *src, GstPad *new_pad, gpointer user_data)
{
    GstElement *depay = GST_ELEMENT(user_data);
    GstPad *sink_pad = gst_element_get_static_pad(depay, "sink");

    if (!sink_pad)
        return;
    if (gst_pad_is_linked(sink_pad))
    {
        gst_object_unref(sink_pad);
        return;
    }

    GstCaps *caps = gst_pad_get_current_caps(new_pad);
    if (!caps)
        caps = gst_pad_query_caps(new_pad, NULL);

    if (caps)
    {
        GstStructure *str = gst_caps_get_structure(caps, 0);
        const gchar *media_type = gst_structure_get_string(str, "media");

        if (g_strcmp0(media_type, "video") == 0)
        {
            if (gst_pad_link(new_pad, sink_pad) == GST_PAD_LINK_OK)
            {
                g_print("[GStreamer] RTSP video pad linked successfully\n");
            }
        }
        gst_caps_unref(caps);
    }
    gst_object_unref(sink_pad);
}

// Handle incoming signaling messages from browser
static void on_ws_message(SoupWebsocketConnection *conn, SoupWebsocketDataType type, GBytes *message, gpointer user_data)
{
    gsize size;
    const gchar *data = g_bytes_get_data(message, &size);

    JsonParser *parser = json_parser_new();
    if (!json_parser_load_from_data(parser, data, size, NULL))
    {
        g_object_unref(parser);
        return;
    }

    JsonObject *root = json_node_get_object(json_parser_get_root(parser));
    const gchar *msg_type = json_object_get_string_member(root, "type");

    if (g_strcmp0(msg_type, "offer") == 0)
    {
        g_print("[Signaling] Received SDP Offer from browser\n");
        const gchar *sdp_str = json_object_get_string_member(root, "sdp");

        GstSDPMessage *sdp;
        gst_sdp_message_new(&sdp);
        gst_sdp_message_parse_buffer((guint8 *)sdp_str, strlen(sdp_str), sdp);

        GstWebRTCSessionDescription *remote_desc = gst_webrtc_session_description_new(GST_WEBRTC_SDP_TYPE_OFFER, sdp);
        g_signal_emit_by_name(app_state.webrtc, "set-remote-description", remote_desc, NULL);
        gst_webrtc_session_description_free(remote_desc);

        GstPromise *promise = gst_promise_new_with_change_func(on_answer_created, NULL, NULL);
        g_signal_emit_by_name(app_state.webrtc, "create-answer", NULL, promise);
    }
    else if (g_strcmp0(msg_type, "candidate") == 0)
    {
        JsonObject *cand_obj = json_object_get_object_member(root, "candidate");
        const gchar *candidate_str = json_object_get_string_member(cand_obj, "candidate");
        guint mlineindex = json_object_get_int_member(cand_obj, "sdpMLineIndex");

        g_signal_emit_by_name(app_state.webrtc, "add-ice-candidate", mlineindex, candidate_str);
        g_print("[ICE] Added browser candidate (mline %u)\n", mlineindex);
    }

    g_object_ref_sink(parser);
    g_object_unref(parser);
}

// Pipeline bus monitor
static gboolean on_bus_message(GstBus *bus, GstMessage *msg, gpointer user_data)
{
    switch (GST_MESSAGE_TYPE(msg))
    {
    case GST_MESSAGE_ERROR:
    {
        GError *err;
        gchar *dbg;
        gst_message_parse_error(msg, &err, &dbg);
        g_printerr("[GStreamer Error] %s: %s\n", GST_OBJECT_NAME(msg->src), err->message);
        g_printerr("[Debug Details] %s\n", dbg ? dbg : "None");
        g_clear_error(&err);
        g_free(dbg);
        break;
    }
    default:
        break;
    }
    return TRUE;
}

// WebSocket initialization on browser connection
static void on_ws_opened(SoupServer *server, SoupServerMessage *msg, const char *path, SoupWebsocketConnection *connection, gpointer user_data)
{
    g_print("[Signaling] Browser connected via WebSocket\n");
    app_state.ws = connection;
    g_object_ref(connection);

    g_signal_connect(connection, "message", G_CALLBACK(on_ws_message), NULL);

    if (app_state.pipeline)
    {
        gst_element_set_state(app_state.pipeline, GST_STATE_NULL);
        gst_object_unref(app_state.pipeline);
        app_state.pipeline = NULL;
        app_state.webrtc = NULL;
    }

    gchar *pipeline_str = g_strdup_printf(
        "webrtcbin name=sendrecv stun-server=stun://stun.l.google.com:19302 "
        "rtspsrc name=rtspsrc location=" RTSP_URL " protocols=tcp+udp latency=300 timeout=5000000 "
        "rtph264depay name=depay ! h264parse config-interval=1 ! "
        "video/x-h264,stream-format=byte-stream,alignment=au ! "
        "rtph264pay config-interval=1 pt=96 aggregate-mode=zero-latency ! "
        "application/x-rtp,media=video,clock-rate=90000,encoding-name=H264,payload=96 ! "
        "queue name=videoqueue");

    GError *error = NULL;
    app_state.pipeline = gst_parse_launch(pipeline_str, &error);
    g_free(pipeline_str);

    if (error)
    {
        g_printerr("[GStreamer Error] %s\n", error->message);
        g_error_free(error);
        return;
    }

    GstBus *bus = gst_element_get_bus(app_state.pipeline);
    gst_bus_add_watch(bus, on_bus_message, NULL);
    gst_object_unref(bus);

    app_state.webrtc = gst_bin_get_by_name(GST_BIN(app_state.pipeline), "sendrecv");
    GstElement *rtspsrc = gst_bin_get_by_name(GST_BIN(app_state.pipeline), "rtspsrc");
    GstElement *depay = gst_bin_get_by_name(GST_BIN(app_state.pipeline), "depay");
    GstElement *videoqueue = gst_bin_get_by_name(GST_BIN(app_state.pipeline), "videoqueue");

    if (rtspsrc && depay)
    {
        g_signal_connect(rtspsrc, "pad-added", G_CALLBACK(on_rtspsrc_pad_added), depay);
        gst_object_unref(rtspsrc);
        gst_object_unref(depay);
    }

    // Connect videoqueue directly to dynamic webrtcbin sink pad
    if (videoqueue && app_state.webrtc)
    {
        GstPad *srcpad = gst_element_get_static_pad(videoqueue, "src");
        GstPad *sinkpad = gst_element_request_pad_simple(app_state.webrtc, "sink_%u");
        if (srcpad && sinkpad)
        {
            if (gst_pad_link(srcpad, sinkpad) == GST_PAD_LINK_OK)
            {
                g_print("[GStreamer] Linked videoqueue to webrtcbin sink pad\n");
            }
            gst_object_unref(srcpad);
            gst_object_unref(sinkpad);
        }
        gst_object_unref(videoqueue);
    }

    g_signal_connect(app_state.webrtc, "on-ice-candidate", G_CALLBACK(on_ice_candidate), NULL);

    gst_element_set_state(app_state.pipeline, GST_STATE_PLAYING);
}

// HTTP handler to serve index.html directly
static void on_http_request(SoupServer *server, SoupServerMessage *msg, const char *path, GHashTable *query, gpointer user_data)
{
    if (g_strcmp0(path, "/") == 0)
    {
        GMappedFile *file = g_mapped_file_new("index.html", FALSE, NULL);
        if (file)
        {
            GBytes *bytes = g_mapped_file_get_bytes(file);
            soup_server_message_set_response(msg, "text/html", SOUP_MEMORY_TAKE,
                                             g_bytes_get_data(bytes, NULL),
                                             g_bytes_get_size(bytes));
            soup_server_message_set_status(msg, SOUP_STATUS_OK, NULL);
            g_mapped_file_unref(file);
        }
        else
        {
            soup_server_message_set_status(msg, SOUP_STATUS_NOT_FOUND, NULL);
        }
    }
    else
    {
        soup_server_message_set_status(msg, SOUP_STATUS_NOT_FOUND, NULL);
    }
}

int main(int argc, char *argv[])
{
    gst_init(&argc, &argv);

    SoupServer *server = soup_server_new("server-header", "webrtc-server", NULL);
    soup_server_add_handler(server, "/", on_http_request, NULL, NULL);
    soup_server_add_websocket_handler(server, "/ws", NULL, NULL, on_ws_opened, NULL, NULL);

    GError *error = NULL;
    soup_server_listen_all(server, 8080, 0, &error);

    if (error)
    {
        g_printerr("Failed to start server: %s\n", error->message);
        g_error_free(error);
        return 1;
    }

    g_print("C WebRTC Server running on http://0.0.0.0:8080/\n");

    GMainLoop *loop = g_main_loop_new(NULL, FALSE);
    g_main_loop_run(loop);

    return 0;
}